/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageHandlingUnitsObjectPageObjectPage journey");

        opaTest("Navigate to ManageHandlingUnitsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheManageHandlingUnitsListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheManageHandlingUnitsListGenerated.onTable().iCheckRows();
            When.onTheManageHandlingUnitsListGenerated.onTable().iPressRow(0);

            Then.onTheManageHandlingUnitsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheManageHandlingUnitsObjectPageGenerated.iCheckSection({ section: "ZQM_R_ManageHandlingUnits" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMWarehouse" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "Product" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStockType" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStockOwner" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EntitledToDisposeParty" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStockUsage" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "StockDocumentCategory" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "ExternalStockDocumentNumber" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "StockItemNumber" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMWorkInProcess" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStockReferenceDocCategory" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStockReferenceDocument" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStockReferenceDocumentItem" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "StockIdentificationNumber" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "WhseQualityInspectionType" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "QualityInspectionDocument" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStorageBin" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "HandlingUnitNumber" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStockQuantityInBaseUnit" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStockQuantityBaseUnit" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMLoadingOrNetWeight" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMLoadingOrNetWeightUnit" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "ShelfLifeExpirationDate" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMGoodsReceiptDateTime" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "WarehouseTimeZone" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStorageType" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "EWMStorageSection" });
            Then.onTheManageHandlingUnitsObjectPageGenerated.onForm({ section: "ZQM_R_ManageHandlingUnits" }).iCheckField({ property: "Plant" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});