/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ManageHandlingUnitsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheManageHandlingUnitsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Warehouse Number");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Product");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Stock Type");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Owner");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Disposal Party");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Usage");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Special Reference Stock Type");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Special Ref. Stk Doc");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("WIP Number");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Reference Document");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Stock ID");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Quality Inspection Type");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Quality Inspection");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Storage Bin");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Handling Unit");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Expiration Date");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Goods Receipt Date");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Storage Type");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Storage Section");
            Then.onTheManageHandlingUnitsListGenerated.onFilterBar().iCheckFilterField("Plant");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheManageHandlingUnitsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheManageHandlingUnitsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheManageHandlingUnitsListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheManageHandlingUnitsListGenerated.onTable().iCheckColumns(undefined, {"EWMWarehouse":{"header":"Warehouse Number"},"Product":{"header":"Product"},"EWMStockType":{"header":"Stock Type"},"EWMStockOwner":{"header":"Owner"},"EntitledToDisposeParty":{"header":"Disposal Party"},"EWMStockUsage":{"header":"Usage"},"StockDocumentCategory":{"header":"Special Reference Stock Type"},"ExternalStockDocumentNumber":{"header":"Special Ref. Stk Doc"},"StockItemNumber":{"header":"Ref. Doc. Item"},"EWMWorkInProcess":{"header":"WIP Number"},"EWMStockReferenceDocCategory":{"header":"Reference Document Category"},"EWMStockReferenceDocument":{"header":"Reference Document"},"EWMStockReferenceDocumentItem":{"header":"Reference Document Item"},"StockIdentificationNumber":{"header":"Stock ID"},"WhseQualityInspectionType":{"header":"Quality Inspection Type"},"QualityInspectionDocument":{"header":"Quality Inspection"},"EWMStorageBin":{"header":"Storage Bin"},"HandlingUnitNumber":{"header":"Handling Unit"},"EWMStockQuantityInBaseUnit":{"header":"Quantity in Base Unit"},"EWMStockQuantityBaseUnit":{"header":"Base Unit of Measure"},"EWMLoadingOrNetWeight":{"header":"Loading Weight"},"EWMLoadingOrNetWeightUnit":{"header":"Weight Unit"},"ShelfLifeExpirationDate":{"header":"Expiration Date"},"EWMGoodsReceiptDateTime":{"header":"Goods Receipt Date"},"WarehouseTimeZone":{"header":"Time Zone"},"EWMStorageType":{"header":"Storage Type"},"EWMStorageSection":{"header":"Storage Section"},"Plant":{"header":"Plant"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheManageHandlingUnitsListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheManageHandlingUnitsListGenerated.onTable().iCheckRows();

            When.onTheManageHandlingUnitsListGenerated.onTable().iPressRow(0);
            Then.onTheManageHandlingUnitsObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});